### ISSUE TITLE
Godwoken support broken

### ISSUE THREAD

**Issue by e00dan** [vintageplayer/highfy-me#12]
![image](https://user-images.githubusercontent.com/4950658/169801323-56ae82eb-bedd-41b0-9cb8-a10e7ac9ece6.png)

Never loads

**Comment by vintageplayer** [comment]
Thanks for raising the issue.  There was a bug with the new contracts added. Fixed and re-deployed.

Please try now.
<img width="1509" alt="Screenshot 2022-05-23 at 4 23 39 PM" src="https://user-images.githubusercontent.com/17234935/169804401-643046a5-0fe5-4149-be0c-63d8c4dfec48.png">

**Comment by e00dan** [comment]
![image](https://user-images.githubusercontent.com/4950658/169812263-ecf8203f-1b24-4d87-bad3-e27c679ee7a7.png)

When trying to send message to 0xd46aC0Bc23dB5e8AfDAAB9Ad35E9A3bA05E092E8 or 0xD173313A51f8fc37BcF67569b463abd89d81844f I get an error. I've created both accounts.

Also, each time I change the account in MetaMask the application tells me to create account again.

At this point the application is close to unusable on Godwoken Testnet. Did you test it yourself before submitting?

**Comment by lazycoder1** [comment]
We have made the application gasless and cross-chain, would love for you to try it out again!
